name: Docker

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build Java image
        run: make build-java

      - name: Build Keycloak image
        run: make build-keycloak

      - name: Log into registry
        run: |
          echo "${{ secrets.docker_password }}" |
            docker login \
              --username "${{ secrets.docker_username }}" \
              --password-stdin

      - name: Push Java image
        run: make push-java

      - name: Push Keycloak image
        run: make push-keycloak