name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build Java image
        run: make build-java

      - name: Build Keycloak image
        run: make build-keycloak

      - name: Build Kafka image
        run: make build-kafka

      - name: Build Ansible image
        run: make build-ansible

      - name: Log into registry
        run: |
          echo "${{ secrets.docker_password }}" |
            docker login \
              --username "${{ secrets.docker_username }}" \
              --password-stdin

      - name: Push Java image
        run: make push-java

      - name: Push Keycloak image
        run: make push-keycloak

      - name: Push Kafka image
        run: make push-kafka

      - name: Push Ansible image
        run: make push-ansible